pages:
  - title: Download
    url: /download.html
  - title: Buy
    url: /buy.html
  - title: Documentation
    url: /documentation/introduction.html
    dir: /documentation/
    subpages:
      - title: Introduction
        url: /documentation/introduction.html
      - title: Language Guide
        url: /documentation/language-guide.html
      - title: Language Reference
        url: /documentation/language-reference.html
  - title: Support
    url: /support.html